# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bryan's research blog for Machine Learning
email: xlibo@connect.ust.hk
description: > # this means to ignore newlines until "baseurl:"
  As a journey towards PhD, this blog intends to record my research/project articles
  /activities. My research is related to Machine Learning, Artificial Intelligence,
  Social Media, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://http://eelxpeng.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  eelxpeng

# Build settings
markdown: kramdown
